### ISSUE TITLE
OSRS HiScore Image folder missing

### ISSUE THREAD

**Issue by SemicolonStruggles** [BladeBTW/StreamTools#1]
Hello,

I am trying to make some improvements to the OSRS HiScore image generator. However the repo appears to be missing the `OSRS HiScore/Images` folder.

It should contain at least the following files:

`Normal.png`
`IM.png`
`HCIM.png`
`DMM.png`
`Tournament.png`
`UIM.png`
`Leagues.png`

Could you please add those?

Thanks!

**Comment by BladeBTW** [comment]
The requested files have been uploaded, thank you kindly for your support!
